language: go
sudo: false
go:
  - "1.11.x"
before_install:
  - go get github.com/mattn/goveralls
script:
  - go build -ldflags="-s -w"
  - go test -race -covermode atomic -coverprofile=profile.cov ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email: false