language: go
sudo: false
go:
  - "1.11.x"
before_install:
  - go get github.com/mattn/goveralls
  - go get ${gobuild_args} ./...
script:
  - go build -ldflags="-s -w"
  - bash coverage.sh
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=.cover/cover.out
notifications:
  email: false