# Cloudflare DDNS main configuration file.
# Uncomment and change as necessary.

# Log verbosity level. Levels are as follows:
# 1 - NONE
# 2 - PRINT
# 3 - ERROR
# 4 - WARN
# 5 - INFO
# 6 - DEBUG
# Defaults to 3.
# loglevel: 3

# IP Resolver configuration
resolver:
  # Do not verify TLS certificates. Defaults to true.
  # noVerify: true

  # List of IP resolvers available. Can add as needed.
  list:
    - name: BigDataCloud
      type: json
      url: https://api.bigdatacloud.net/data/client-ip
      jsonPath: ipString
    - name: ICanHazIP
      type: text
      url: http://icanhazip.com
    - name: IfconfigMe
      type: text
      url: https://ifconfig.me/ip
    - name: IPAPICo
      type: text
      url: https://ipapi.co/ip
    - name: Ipify
      type: text
      url: https://api.ipify.org?format=text
    - name: MyExternalIP
      type: text
      url: https://myexternalip.com/raw
    - name: MyIP
      type: json
      url: https://api.myip.com
      jsonPath: ip
    - name: WhatIsMyIPAddress
      type: text
      url: http://ipv4bot.whatismyipaddress.com
    - name: WTFIsMyIP
      type: text
      url: https://wtfismyip.com/text

# Cloudflare configuration
cloudflare:
  # The email address you use to log into cloudflare.com. There is no default.
  email: <your-cloudflare-email>
  # Your API key. There is no default.
  apiKey: <your-cloudflare-api-key>
  # Your Zone ID. There is no default.
  zoneID: <your-cloudflare-zone-id>
  # List of the hostnames you would like to update. There is no default.
  hostnames:
    - <hostname-1>
    - <hostname-2>

worker:
  # Check interval in seconds.
  # Calculated minimum: 300 / number of resolvers (minimum 5 minutes round interval)
  # Absolute minimum: 30
  # Maximum: 4294967295 (uint32 max value)
  # Recommended: auto (will automatically calculate optimum interval)
  # Defaults to auto
  # checkInterval: auto

# Notifier configuration
notifier:
  # If This Then That
  ifttt:
    # Maker Webhook
    webhook:
      # Set this to true to activate. Defaults to false.
      # active: false
      
      # Your maker key. Login to IFTTT and go to https://ifttt.com/maker_webhooks/settings to get yours.
      # There is no default.
      # makerKey: <your-maker-key-here>
      
      # Your event type. Can be anything. Defaults to cf_ddns_update
      # eventName: cf_ddns_update
